# Golden Raspberry Awards API Configuration
spring:
  application:
    name: golden-raspberry-awards-api

  datasource:
    url: jdbc:h2:mem:goldenraspberry
    driver-class-name: org.h2.Driver
    username: admin
    password: "admin" # NOTE: In a production environment, I would put it in a vault or environment variable.

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
    time-zone: UTC

  security:
    headers:
      frame: deny
      content-type: true
      xss-protection: true

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    com.emikaelsilveira.goldenraspberry: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/golden-raspberry-api.log
    max-size: 10MB
    max-history: 10

app:
  name: Golden Raspberry Awards API
  version: 1.0.0
  description: RESTful API for managing Golden Raspberry Awards data
  contact:
    name: Golden Raspberry Awards API Team
    email: emikael.silveira@gmail.com
  csv:
    file-path: movielist.csv
    encoding: UTF-8
  security:
    api-key: 96babb1d-888d-4336-bceb-e67487862bb3 # NOTE - In a production environment, I would put it in a vault or environment variable.