spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    com.emikaelsilveira.goldenraspberry: DEBUG
    org.hibernate.SQL: DEBUG